spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.campusgo.client.UserClient: DEBUG
    feign: DEBUG

feign:
  client:
    config:
      user-service:
        loggerLevel: FULL


