server:
  port: 9008

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost:3306/campus_admin?useSSL=false&serverTimezone=Asia/Singapore&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.mybatis: debug