spring:
  application:
    name: merchant-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    config:
      profile: ${SPRING_CLOUD_CONFIG_PROFILE:dev}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}


