spring:
  profiles:
    active: dev
  application:
    name: admin-service
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

