spring:
  application:
    name: runner-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/